# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [2]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [73]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)
print a
print b
print c
a=a+1
print a
a=a*3
print a

[ 0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[[3 2 9 8]
  [6 5 7 3]
  [2 4 3 1]]

 [[4 6 9 8]
  [4 6 4 5]
  [5 5 3 3]]]
[ 1.  1.  1.]
[ 3.  3.  3.]


What are these functions?

    arange?

In [4]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[6, 4, 8, 8],
         [2, 3, 2, 9],
         [3, 8, 1, 1]],
 
        [[4, 1, 6, 4],
         [8, 8, 2, 7],
         [5, 5, 7, 4]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [5]:
## Arithmetic in arrays is element wise

In [6]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [7]:
c = a-b
c

array([20, 29, 38, 47])

In [8]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [9]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [74]:
a

array([ 3.,  3.,  3.])

In [75]:
a[2:5]
print a[-1]

3.0


In [12]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [13]:
b = np.random.randint(1,100,(4,4))

In [81]:
b=np.array([[34, 80, 40, 46],
       [93,  9, 55,  7],
       [ 4, 23,  7, 44],
       [15, 54, 26, 38]])

In [83]:
# Guess the output
#print(b[2,3])
# print(b[0,0])
print(b)
print(b[1,2])

[[34 80 40 46]
 [93  9 55  7]
 [ 4 23  7 44]
 [15 54 26 38]]
55


In [85]:
print(b[0:3,0:2])

[[34 80]
 [93  9]
 [ 4 23]]


In [17]:
b[1:3,:]

array([[93,  9, 55,  7],
       [ 4, 23,  7, 44]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [89]:
dates = pd.date_range('20140101',periods=6, freq='M')
dates

DatetimeIndex(['2014-01-31', '2014-02-28', '2014-03-31', '2014-04-30',
               '2014-05-31', '2014-06-30'],
              dtype='datetime64[ns]', freq='M')

In [20]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [21]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  1.276718  0.450282  1.342259 -0.020532
2014-01-02  0.383592 -0.717121  0.777946  1.240036
2014-01-03  0.612695  0.737287 -0.407388 -0.588682
2014-01-04  1.067770 -0.270669 -0.190949  1.219571
2014-01-05 -1.356961 -0.094120 -1.108320  0.254007
2014-01-06  0.157567 -0.105155  0.234984  1.544298

In [22]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [23]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [90]:
df.head(n=7)

A      B         C         D
0  foo    one  0.134435 -1.528111
1  bar    one  0.504807  0.584661
2  foo    two -1.041724 -0.349757
3  bar  three  0.318612 -1.677094
4  foo    two -1.031122  1.264653
5  bar    two  0.303792  0.210513
6  foo    one -1.439173 -0.146706

In [25]:
df.tail()

A         B         C         D
2014-01-02  0.383592 -0.717121  0.777946  1.240036
2014-01-03  0.612695  0.737287 -0.407388 -0.588682
2014-01-04  1.067770 -0.270669 -0.190949  1.219571
2014-01-05 -1.356961 -0.094120 -1.108320  0.254007
2014-01-06  0.157567 -0.105155  0.234984  1.544298

In [26]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [27]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.356897  0.000084  0.108089  0.608117
std    0.937507  0.520343  0.874388  0.848829
min   -1.356961 -0.717121 -1.108320 -0.588682
25%    0.214074 -0.229291 -0.353278  0.048103
50%    0.498144 -0.099637  0.022018  0.736789
75%    0.954001  0.314181  0.642205  1.234920
max    1.276718  0.737287  1.342259  1.544298

In [28]:
df.sort_values(by='B')
df

A         B         C         D
2014-01-01  1.276718  0.450282  1.342259 -0.020532
2014-01-02  0.383592 -0.717121  0.777946  1.240036
2014-01-03  0.612695  0.737287 -0.407388 -0.588682
2014-01-04  1.067770 -0.270669 -0.190949  1.219571
2014-01-05 -1.356961 -0.094120 -1.108320  0.254007
2014-01-06  0.157567 -0.105155  0.234984  1.544298

### Selection

In [29]:
df[['A','B']]

A         B
2014-01-01  1.276718  0.450282
2014-01-02  0.383592 -0.717121
2014-01-03  0.612695  0.737287
2014-01-04  1.067770 -0.270669
2014-01-05 -1.356961 -0.094120
2014-01-06  0.157567 -0.105155

In [30]:
df[0:3]

A         B         C         D
2014-01-01  1.276718  0.450282  1.342259 -0.020532
2014-01-02  0.383592 -0.717121  0.777946  1.240036
2014-01-03  0.612695  0.737287 -0.407388 -0.588682

In [31]:
# By label
df.loc[dates[0]]

A    1.276718
B    0.450282
C    1.342259
D   -0.020532
Name: 2014-01-01 00:00:00, dtype: float64

In [32]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  1.276718  0.450282
2014-01-02  0.383592 -0.717121
2014-01-03  0.612695  0.737287
2014-01-04  1.067770 -0.270669
2014-01-05 -1.356961 -0.094120
2014-01-06  0.157567 -0.105155

In [33]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -0.717121
2014-01-03  0.737287
2014-01-04 -0.270669

In [34]:
# Fast access to scalar
df.at[dates[1],'B']

-0.71712112965192598

In [35]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04  1.067770 -0.270669 -0.190949  1.219571
2014-01-05 -1.356961 -0.094120 -1.108320  0.254007
2014-01-06  0.157567 -0.105155  0.234984  1.544298

### Boolean Indexing

In [92]:
df[df.A > 0] # Basically a 'where' operation

A      B         C         D
0  foo    one  0.134435 -1.528111
1  bar    one  0.504807  0.584661
2  foo    two -1.041724 -0.349757
3  bar  three  0.318612 -1.677094
4  foo    two -1.031122  1.264653
5  bar    two  0.303792  0.210513
6  foo    one -1.439173 -0.146706
7  foo  three -1.215308 -0.579149

### Setting

In [37]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [38]:
df_posA

A         B         C         D
2014-01-01  1.276718  0.450282  1.342259 -0.020532
2014-01-02  0.383592 -0.717121  0.777946  1.240036
2014-01-03  0.612695  0.737287 -0.407388 -0.588682
2014-01-04  1.067770 -0.270669 -0.190949  1.219571
2014-01-05  1.356961  0.094120  1.108320 -0.254007
2014-01-06  0.157567 -0.105155  0.234984  1.544298

In [39]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [40]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [41]:
df['F'] = s1

In [42]:
df

A         B         C         D    F
2014-01-01  1.276718  0.450282  1.342259 -0.020532  NaN
2014-01-02  0.383592 -0.717121  0.777946  1.240036  1.0
2014-01-03  0.612695  0.737287 -0.407388 -0.588682  2.0
2014-01-04  1.067770 -0.270669 -0.190949  1.219571  3.0
2014-01-05 -1.356961 -0.094120 -1.108320  0.254007  4.0
2014-01-06  0.157567 -0.105155  0.234984  1.544298  5.0

### Missing Data

In [43]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [44]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [45]:
df1

A         B         C         D    F    E
2014-01-01  1.276718  0.450282  1.342259 -0.020532  NaN  1.0
2014-01-02  0.383592 -0.717121  0.777946  1.240036  1.0  1.0
2014-01-03  0.612695  0.737287 -0.407388 -0.588682  2.0  NaN
2014-01-04  1.067770 -0.270669 -0.190949  1.219571  3.0  NaN

In [46]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [47]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean   0.356897  0.000084  0.108089  0.608117  3.000000
std    0.937507  0.520343  0.874388  0.848829  1.581139
min   -1.356961 -0.717121 -1.108320 -0.588682  1.000000
25%    0.214074 -0.229291 -0.353278  0.048103  2.000000
50%    0.498144 -0.099637  0.022018  0.736789  3.000000
75%    0.954001  0.314181  0.642205  1.234920  4.000000
max    1.276718  0.737287  1.342259  1.544298  5.000000

In [48]:
df.mean(),df.mean(1) # Operation on two different axes

(A    0.356897
 B    0.000084
 C    0.108089
 D    0.608117
 F    3.000000
 dtype: float64, 2014-01-01    0.762182
 2014-01-02    0.536891
 2014-01-03    0.470782
 2014-01-04    0.965145
 2014-01-05    0.338921
 2014-01-06    1.366339
 Freq: D, dtype: float64)

### Applying functions

In [49]:
df

A         B         C         D    F
2014-01-01  1.276718  0.450282  1.342259 -0.020532  NaN
2014-01-02  0.383592 -0.717121  0.777946  1.240036  1.0
2014-01-03  0.612695  0.737287 -0.407388 -0.588682  2.0
2014-01-04  1.067770 -0.270669 -0.190949  1.219571  3.0
2014-01-05 -1.356961 -0.094120 -1.108320  0.254007  4.0
2014-01-06  0.157567 -0.105155  0.234984  1.544298  5.0

In [50]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  1.276718  0.450282  1.342259 -0.020532   NaN
2014-01-02  1.660310 -0.266839  2.120204  1.219504   1.0
2014-01-03  2.273005  0.470448  1.712816  0.630822   3.0
2014-01-04  3.340776  0.199778  1.521868  1.850394   6.0
2014-01-05  1.983815  0.105659  0.413548  2.104401  10.0
2014-01-06  2.141382  0.000504  0.648532  3.648699  15.0

In [51]:
df.apply(lambda x: x.max() - x.min())

A    2.633679
B    1.454408
C    2.450579
D    2.132980
F    4.000000
dtype: float64

In [52]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [53]:
np.random.randn(10,4)

array([[ 0.92346835,  0.55387477, -0.83690092,  0.08533449],
       [ 0.2207515 ,  0.27235299, -0.97447509,  1.11442034],
       [ 1.2792915 , -0.49965982,  0.93995364,  0.47570579],
       [ 0.31271353, -1.37493223,  1.57216341, -0.30561941],
       [ 0.19792806,  0.74019037,  0.07041744,  0.34530806],
       [ 0.19844296, -0.57765881, -0.64112533,  1.08095672],
       [ 0.5157661 ,  0.99776849, -0.64384137, -0.11585594],
       [ 1.89338015, -0.48185451, -1.48889695,  0.55449136],
       [ 0.99162738, -1.05550691,  0.92247186,  0.28743274],
       [-1.82237846,  0.50987231, -0.00785454, -0.67505967]])

In [54]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.595390 -0.222317  0.384326  0.026412
1 -0.738188 -1.617367  0.806541  1.637132
2 -0.410942 -0.377680 -0.291477 -0.879479
3  0.652585  0.630683  0.581174 -0.429432
4  0.407611 -1.433475  1.447854  0.289921
5  0.801424  1.297989  1.298444  1.892693
6  1.093256  1.929476 -0.386466  0.140605
7  1.477468  1.877740  1.808949  0.488504
8 -0.497748 -1.348416 -0.629825  0.097825
9 -0.924641  0.017891  1.241510 -0.153186

In [55]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -0.595390 -0.222317  0.384326  0.026412
 1 -0.738188 -1.617367  0.806541  1.637132
 2 -0.410942 -0.377680 -0.291477 -0.879479,
           0         1         2         3
 3  0.652585  0.630683  0.581174 -0.429432
 4  0.407611 -1.433475  1.447854  0.289921
 5  0.801424  1.297989  1.298444  1.892693
 6  1.093256  1.929476 -0.386466  0.140605,
           0         1         2         3
 7  1.477468  1.877740  1.808949  0.488504
 8 -0.497748 -1.348416 -0.629825  0.097825
 9 -0.924641  0.017891  1.241510 -0.153186]

In [56]:
pd.concat(pieces)

0         1         2         3
0 -0.595390 -0.222317  0.384326  0.026412
1 -0.738188 -1.617367  0.806541  1.637132
2 -0.410942 -0.377680 -0.291477 -0.879479
3  0.652585  0.630683  0.581174 -0.429432
4  0.407611 -1.433475  1.447854  0.289921
5  0.801424  1.297989  1.298444  1.892693
6  1.093256  1.929476 -0.386466  0.140605
7  1.477468  1.877740  1.808949  0.488504
8 -0.497748 -1.348416 -0.629825  0.097825
9 -0.924641  0.017891  1.241510 -0.153186

In [57]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -0.595390 -0.222317  0.384326  0.026412
1 -0.738188 -1.617367  0.806541  1.637132
2 -0.410942 -0.377680 -0.291477 -0.879479
3  0.652585  0.630683  0.581174 -0.429432
4  0.407611 -1.433475  1.447854  0.289921
5  0.801424  1.297989  1.298444  1.892693
6  1.093256  1.929476 -0.386466  0.140605
7  1.477468  1.877740  1.808949  0.488504
8 -0.497748 -1.348416 -0.629825  0.097825
9 -0.924641  0.017891  1.241510 -0.153186

### Grouping


In [58]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [59]:
df

A      B         C         D
0  foo    one  0.134435 -1.528111
1  bar    one  0.504807  0.584661
2  foo    two -1.041724 -0.349757
3  bar  three  0.318612 -1.677094
4  foo    two -1.031122  1.264653
5  bar    two  0.303792  0.210513
6  foo    one -1.439173 -0.146706
7  foo  three -1.215308 -0.579149

In [60]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one    0.504807  0.584661
    three  0.318612 -1.677094
    two    0.303792  0.210513
foo one   -1.304738 -1.674818
    three -1.215308 -0.579149
    two   -2.072846  0.914896

### Reshaping

In [61]:
# You can also stack or unstack levels

In [62]:
a = df.groupby(['A','B']).sum()

In [63]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  0.504807  0.318612  0.303792  0.584661 -1.677094  0.210513
foo -0.652369 -1.215308 -1.036423 -0.837409 -0.579149  0.457448

### Time Series


In [64]:
import pandas as pd
import numpy as np

In [65]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [66]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [67]:
ts

2014-01-01 00:00:00     14
2014-01-01 00:00:01    251
2014-01-01 00:00:02    390
2014-01-01 00:00:03    206
2014-01-01 00:00:04    373
2014-01-01 00:00:05    281
2014-01-01 00:00:06     36
2014-01-01 00:00:07     63
2014-01-01 00:00:08    249
2014-01-01 00:00:09    327
2014-01-01 00:00:10      5
2014-01-01 00:00:11    212
2014-01-01 00:00:12    115
2014-01-01 00:00:13    279
2014-01-01 00:00:14    438
2014-01-01 00:00:15     40
2014-01-01 00:00:16    413
2014-01-01 00:00:17    134
2014-01-01 00:00:18     96
2014-01-01 00:00:19    177
2014-01-01 00:00:20    164
2014-01-01 00:00:21     89
2014-01-01 00:00:22    317
2014-01-01 00:00:23    457
2014-01-01 00:00:24    453
2014-01-01 00:00:25     54
2014-01-01 00:00:26    180
2014-01-01 00:00:27    201
2014-01-01 00:00:28    368
2014-01-01 00:00:29    271
                      ... 
2014-01-01 00:01:10    336
2014-01-01 00:01:11    157
2014-01-01 00:01:12    153
2014-01-01 00:01:13    313
2014-01-01 00:01:14    158
2014-01-01 00:01:15    355
2

In [68]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    217.183333
2014-01-01 00:01:00    259.900000
Freq: T, dtype: float64

In [69]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-69-5c9240a56f62>, line 2)

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas