Text Mining: Vectorization, TF-IDF, & Cosine Similarity
=====

1. The Vector Space Model
====

2. Vector Normalization
====

3. Term Frequency - Inverse Document Frequency (TF-IDF)
====

4. Cosine Similarity
====
***

####This Notebook is based upon the tutorials found at Pyevolve, by Christian S. Perone:

####http://blog.christianperone.com/?p=1589

---
1. The Vector Space Model (VSM)
=====

- In information retrieval or text mining, the 'term frequency – inverse document frequency' also called tf-idf, is a well known method to evaluate how important a word is within a corpus of documents. 

- Tf-idf is also a very interesting way to convert the textual representation of information into a Vector Space Model (VSM), or into sparse features.

### 1.1 Vector Space

- The first step in creating a representation of a document in vector space is to create a dictionary of terms

- To do this, you simply select all terms from the document, estimate their frequencies and use these frequencies as numerical vectors

- Stop words will be removed

####An extremely basic document space:

#####Training Document Set:

d1: The sky is blue.

d2: The sun is bright.

#####Test Document Set:

d3: The sun in  the sky is bright.

d4: We can see the shining sun, the bright sun.

- Create a dictionary of words, otherwise known as an index vocabulary

- Using the documents d1 and d2 from the training document set, we’ll have the following index vocabulary, denoted as $E(t)$, where the $t$ is a word:

$E(t) = \left\{\begin{matrix} 
1, & \text{if }t\text{ is } "blue" \\
2, & \text{if }t\text{ is } "sun" \\
3, & \text{if }t\text{ is } "bright" \\
4, & \text{if }t\text{ is } "sky"\end{matrix}\right.$

- $E(t)$ converts a word or term to an integer

- Converting the training documents is a Python "fit"

- Using the index vocabulary we can convert the test document set into a vector space, which is a Python "transform"

- For example, the first vector value will represent frequency of the word 'blue'

- Term Frequency (requiring $2$ arguments - a term, $t$, and a document $d$) is defined as:

$tf(t, d) = \sum_{x \in d}fr(x, t)$

where $fr(x, t) = \left\{\begin{matrix} 1, & \text{if }t = x \\ 0, & \text{otherwise} \end{matrix}\right.$

- $x$ is all the terms or words in the document

- it is just a frequency counter

- $tf(t,d)$ returns how many times the term t is present in the document d. 

- For example: $tf(\text{'sun'}, d4) = 2$, since we have only two occurrences of the term “sun” in the document d4.

####The Document Vector

- A Document Vector is defined as:

$\overrightarrow{v_{d_{n}}} = (tf(t_{1}, d_{n}), tf(t_{2}, d_{n}), tf(t_{3},d_{n}),...,tf(t_{n}, d_{n}))$

- each dimension of the document vector represents the term frequency of a word in the index vocabularly from the document

- For example: the $tf(t_1,d_2)$ represents the frequency-term of term $1$ or $t_1$ ('blue' in our example index vocabulary) in the document $d_2$.

####The Transform:

- Representing documents $d_3$ and $d_4$ (the test documents) as vectors:

$\overrightarrow{v_{d_{3}}} = (tf(t_{1}, d_{3}), tf(t_{2}, d_{3}), tf(t_{3},d_{3}),...,tf(t_{n}, d_{3}))$

$\overrightarrow{v_{d_{4}}} = (tf(t_{1}, d_{4}), tf(t_{2}, d_{4}), tf(t_{3},d_{4}),...,tf(t_{n}, d_{3}))$

$\overrightarrow{v_{d_{3}}} = (tf(blue, d_{3}), tf(sun, d_{3}), tf(bright,d_{3}), tf(sky, d_{3}))$

$\overrightarrow{v_{d_{4}}} = (tf(blue, d_{4}), tf(sun, d_{4}), tf(bright,d_{4}), tf(sky, d_{4}))$

#####Which evaluates to:

$\overrightarrow{v_{d_{3}}} = (0,1,1,1)$

$\overrightarrow{v_{d_{4}}} = (0,2,1,0)$

- recall documents $d_3$ and $d_4$ are:

d3: The sun in the sky is bright.

d4: We can see the shining sun, the bright sun.

- The resulting vector $v_{d_3}$ shows that we have, in order, 0 occurrences of the term “blue”, 1 occurrence of the term “sun”, and so on. 

- In vector $v_{d_3}$, we have 0 occurences of the term “blue”, 2 occurrences of the term “sun”, etc.

- each document is now represented as a vector

- the corpus of documents can now be represented by a matrix containing the vectors

- the matrix will have shape $D \times F$, where |D| is the cardinality of the document space, or how many documents there are, and the F is the number of features, in our case represented by the index vocabulary size

- an example of the matrix representation of the vectors described above is:

$M_{|D| \times F} = \begin{bmatrix} 0 & 1 & 1 & 1 \\ 0 & 2 & 1 & 0 \end{bmatrix} $

- such matrices, representing the term frequencies, tend to be very sparse (with majority of terms zeroed), and that’s why they are commonly represented as sparse matrices

### 1.2 Now, in Python

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
vectorizer = CountVectorizer()

print vectorizer

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [3]:
train_set = ("The sky is blue.",
             "The sun is bright.")

In [4]:
test_set = ("The sun in the sky is bright.",
            "We can see the shining sun, the bright sun.")

In [5]:
vectorizer.fit_transform(train_set)
print vectorizer.vocabulary_

{u'blue': 0, u'bright': 1, u'sun': 4, u'is': 2, u'sky': 3, u'the': 5}


#####*Q: What do you notice about the index vocabulary?*

In [6]:
#what parameter do we need to set when instantiating the CountVectorizer object instance?
vectorizer = CountVectorizer(stop_words = "english")

In [7]:
count_vectors = vectorizer.fit_transform(train_set)
print vectorizer.vocabulary_

{u'blue': 0, u'sun': 3, u'bright': 1, u'sky': 2}


In [8]:
print count_vectors

  (0, 2)	1
  (0, 0)	1
  (1, 3)	1
  (1, 1)	1


#####Now that we have constructed our vocabulary with the fit function, let's pass our test set through that vocabulary using the transform function:

#####Remember its vectorizer.transform (not fit!!)

In [9]:
sparse_matrix = vectorizer.transform(test_set)
print sparse_matrix

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (1, 1)	1
  (1, 3)	2


#####Note that the sparse matrix created, called "sparse_matrix" is a Scipy sparse matrix, with elements stored in a Coordinate format. But we can convert it into a dense format:

In [10]:
sparse_matrix.todense()

matrix([[0, 1, 1, 1],
        [0, 1, 0, 2]])

####Each row in the above matrix represents a document in our test set ($d3$ and $d4$). 

####So, this gives us a (very basic) matrix of term frequencies in our test documents. 

####We have mapped our text documents into a vector space!
---

---

2. Vector Normalization
=====
***

- the main problem with the term-frequency approach is that it scales up frequent terms and scales down rare terms, which are empirically more informative than the high frequency terms. 

- The basic intuition is that a term that occurs frequently in many documents is not a good discriminator. 

- The important question, if the aim is to classify documents, is why you would emphasize a term which is almost present in the entire corpus of all your documents?

####Term Frequency minus Inverse Document Frequency (tf-idf) solves this problem

- tf-idf provides an indicator of the importance of a word found within a document across the entire corpus of documents 

- tf-idf incorporates local and global parameters; it takes into consideration not only the local term frequency but also the term frequency within the document collection (global). 

- tf-idf basically weights the frequent terms less than than the rarer terms using a logarithmic scale, because a term that occurs 10 times more than another isn’t 10 times more important 

#####Normalized Term Frequency

- the use of simple term frequency could lead us to problems like *keyword spamming*

- keyword spamming occurs when we have a repeated term in a document whose purpose is to improve the document's ranking on an Information Retrieval (IR) system

- term repeating can also create a bias towards long documents, making them look more important than they are just because of the high frequency of a term in the document

- to overcome this problem the vector space of a document is usually normalized 

#####Normalizing the Document Vectors

$\overrightarrow{v_{d_{4}}} = (0, 2, 1, 0)$

- normalizing a vector means making it's length $1$

- a normalized vector is denoted using the 'hat' notation:

$\hat{v}$

- The definition of $\hat{v}$ is:

$\hat{v} = \frac{\overrightarrow{v}}{\|\overrightarrow{v}\|_{p}}$

- $\overrightarrow{v}$ is the vector going to be normalized and the $\|\overrightarrow{v}\|_{p}$ is the norm (magnitude, length) of the vector $\overrightarrow{v}$ in the $L^{p}$ space.

####Diagrammatically:

<img src="./Assets/10.png" />

####Calculation of 'length' and Lebesque Spaces

- to understand this, you must understand the motivation of the $L^{p}$ spaces, also called Lebesgue spaces

- we have already seen examples of Lebesgue spaces in terms of regression and classification coefficient penalties!!

- L1 and L2 norm

####Lebesgue Spaces

<img src="./Assets/11.png" />

#####The L2 Norm:

$\|\overrightarrow{v}\|=\sqrt{v^{2}_{1} + v^{2}_{2} + v^{2}_{3} + ... + v^{2}_{n}}$

- this is *NOT* the only way to define length

- that’s why you see (sometimes) a number $p$ together with the norm notation, like in $|v|^{p}$. 

- that’s because it could be generalized as:

$\|\overrightarrow{v}\|_{p} = \left(|v_{1}|^{p} + |v_{2}|^{p} + |v_{3}|^{p} + ... + |v_{n}|^{p}\right)^{\frac{1}{p}}$

- when you see L2-norm, it means Euclidean norm, or a norm with p=2 (this is the most common norm used)

- if you see an unqualified length measure (without the $p$ number), you assume L2.

- L1-norm, $p=1$, is defined as:

$\|\overrightarrow{v}\|_{1} = \left(|v_{1}| + |v_{2}| + |v_{3}| + ... + |v_{n}|\right)$

- which is nothing more than a simple sum of the components of the vector, also known as Taxicab distance, also known as Manhattan distance.

<img src="./Assets/manhattan_distance.svg" />

#####Taxicab geometry versus Euclidean distance

- using Taxicab distance the blue, red and yellow lines pictured have the same length (12) for the same route. 

- Using L2-norma, the green line has length $\sqrt{36 + 36} = 8.48$.

- Note that you can also use any norm to normalize a vector.

- Let's use L2, which is also the default in sklearn. 

####Normalizing the Vectors

$\hat{v} = \frac{\overrightarrow{v}}{\| \overrightarrow{v} \|_{p}}$

$\hat{v_{d_{4}}} = \frac{\overrightarrow{v_{d_{4}}}}{\| \overrightarrow{v_{d_{4}}} \|_{2}}$

$\hat{v_{d_{4}}} = \frac{(0,2,1,0)}{\sqrt{0^{2} + 2^{2} + 1^{2} + 0^{2}}}$

$\hat{v_{d_{4}}} = \frac{(0,2,1,0)}{\sqrt{5}}$

$\hat{v_{d_{4}}} = (0.0, 0.89, 0.45, 0.0)$

- $\hat{v_{d_{4}}}$ now has length 1

---

---

3 The Term Frequency - Inverse Document Frequency (TF-IDF) Weight
=====
***

#####Training Document Set:

d1: The sky is blue

d2: The sun is bright

#####Test Document Set:

d3: The sun in the sky is bright

d4: We can see the shining sun, the bright sun


####With terms:

blue, sun, bright, sky

- the document space can be defined then as $D = {d1, d2, ..., dn}$ where $n$ is the number of documents in our corpus, and in our case as $D_{train} = {d1, d2}$ and $D_{test} = {d3, d4}$

- the cardinality of our document space is defined by $|D_{train}| = 2$ and $|D_{test}| = 2$, since we have only 2 two documents for training and testing

- the training and test sets do not need to have the same cardinality

#####idf (inverse document frequency) is defined:

$idf(t) = log\frac{|D|}{1+|\{d:t \in d\}|}$

- where $|\{d : t \in d\}|$ is the number of documents where the term t appears

- add 1 into the formula to avoid zero-division.

#####The formula for the tf-idf is then:

$tf-idf(t) = tf(t,d) \times idf(t)$

#####*This formula has an important consequence: a high weight of the tf-idf calculation is reached when we have a high term frequency (tf) in the given document (local parameter) and a low document frequency of the term in the whole collection (global parameter).*

- let’s calculate the idf for each feature present in the feature matrix with the term frequency we have calculated in the first section above: 

$M_{train} = \begin{bmatrix} 0 & 1 & 1 & 1 \\ 0 & 2 & 1 & 0 \end{bmatrix}$

- since we have 4 features, we have to calculate $idf(t1)$, $idf(t2)$, $idf(t3)$, $idf(t4)$:

$idf(t_{1}) = log\frac{|D|}{1+|\{d:t\in d\}|} = ln\frac{2}{1} = 0.6931$

$idf(t_{2}) = log\frac{|D|}{1+|\{d:t\in d\}|} = ln\frac{2}{3} = -0.4055$

$idf(t_{3}) = log\frac{|D|}{1+|\{d:t\in d\}|} = ln\frac{2}{3} = -0.4055$

$idf(t_{4}) = log\frac{|D|}{1+|\{d:t\in d\}|} = ln\frac{2}{2} = 0.000$

- these idf weights can be represented by a vector as:

$\overrightarrow{idf_{train}} = (0.6931, -0.4055, -0.4055, 0.0000)$

- now that we have our matrix with the term frequency $M_{train}$ and the vector representing the idf for each feature of our matrix $idf_{train}$, we can calculate our tf-idf weights. 

- what we have to do is a simple multiplication of each column of the matrix $M_{train}$ with the respective $idf_{train}$ vector dimension. 

- To do that, we can create a square diagonal matrix called $M_{idf}$ with both the vertical and horizontal dimensions equal to the vector $idf_{train}$ dimension:

$M_{idf} = \begin{bmatrix} 0.6931 & 0 & 0 & 0 \\ 0 & -0.4055 & 0 & 0 \\ 0 & 0 & -0.4055 & 0 \\ 0 & 0 & 0 & 0.000 \end{bmatrix}$

- and then multiply it by the term frequency matrix, so the final result can be defined then as:

$M_{tf-idf} = M_{train} \times M_{idf}$

#####Matrix multiplication isn’t commutative, the result of A x B will be different than the result of the B x A, and this is why the $M_{idf}$ is on the right side of the multiplication, to accomplish the desired effect of multiplying each idf value to its corresponding feature:

$\begin{bmatrix} tf(t_{1}, d_{1}) & tf(t_{2}, d_{1}) & tf(t_{3}, d_{1}) & tf(t_{4}, d_{1}) \\ tf(t_{1}, d_{2}) & tf(t_{2}, d_{2}) & tf(t_{3}, d_{2}) & tf(t_{4}, d_{2})  \end{bmatrix} \times \begin{bmatrix} idf(t_{1}) & 0 & 0 & 0 \\ 0 & idf(t_{2}) & 0 & 0 \\ 0 & 0 & idf(t_{3}) & 0 \\ 0 & 0 & 0 & idf(t_{4}) \end{bmatrix}$

#####Let’s see now a concrete example of this multiplication:

$M_{tf-idf} = M_{train} \times M_{idf} = \begin{bmatrix} 0 & 1 & 1 & 1 \\ 0 & 2 & 1 & 0 \end{bmatrix} \times \begin{bmatrix} 0.6931 & 0 & 0 & 0 \\ 0 & -0.4055 & 0 & 0 \\ 0 & 0 & -0.4055 & 0 \\ 0 & 0 & 0 & 0.000 \end{bmatrix} = \begin{bmatrix} 0 & -0.4055 & -0.4055 & 0 \\ 0 & -0.8109 & -0.4055 & 0 \end{bmatrix}$

- finally, we can apply our L2 normalization process to the $M_{tf-idf}$ matrix. 

- note that this normalization is “row-wise” because we’re going to handle each row of the matrix as a separated vector to be normalized, and not the matrix as a whole:

$M_{tf-idf} = \frac{M_{tf-idf}}{\|M_{tf-idf} \|_{2}} = \begin{bmatrix} 0 & -0.7071 & -0.7071 & 0 \\ 0 & -0.8944 & -0.4472 & 0 \end{bmatrix}$

- and that is the normalized tf-idf weight of our testing document set, which is actually a collection of unit vectors. 

- if we take the L2-norm of each row of the matrix, we’ll see that they all have a L2-norm of 1.

### 3.1 Now in Python


- The sklearn routine produces the vocabulary in a different order to what was used above
- The first step is to create our training and testing document set and computing the term frequency matrix:

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

train_set = ["The sky is blue.", "The sun is bright."]
test_set = ["The sun in the sky is bright.", "We can see the shining sun, the bright sun."]

count_vectorizer = CountVectorizer(stop_words="english")
mcv = count_vectorizer.fit_transform(train_set)
print "Vocabulary:", count_vectorizer.vocabulary_

Vocabulary: {u'blue': 0, u'sun': 3, u'bright': 1, u'sky': 2}


In [12]:
freq_term_matrix = count_vectorizer.transform(test_set)
print freq_term_matrix.todense()

[[0 1 1 1]
 [0 1 0 2]]


- Now that we have the frequency term matrix (called "freq_term_matrix"), we can instantiate the tf-idf Transformer

- The tf-idf transformer is going to be responsible for calculating the tf-idf weights for our term frequency matrix

- Note that we’ve specified the norm as L2. This is optional (actually the default is L2-norm)

- Also note that we can see the calculated idf weight by accessing the internal attribute called idf_ 

In [13]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(norm="l2", use_idf=True)
tfidf.fit(freq_term_matrix)

print "IDF:", tfidf.idf_

IDF: [ 2.09861229  1.          1.40546511  1.        ]


In [67]:
#help(TfidfTransformer)

- Now that the fit() method has calculated the idf for the matrix, let’s transform the freq_term_matrix to the tf-idf weight matrix:

In [68]:
tf_idf_matrix = tfidf.transform(freq_term_matrix)
print tf_idf_matrix.todense()

[[ 0.          0.50154891  0.70490949  0.50154891]
 [ 0.          0.4472136   0.          0.89442719]]


- note that scikit-learn provides a function to do the vectorizing and tf-idf matrix calculation all in one, you can use TfidfVectorizer. 

- However, we must pass in a dictionary unless we want the dictionary to be learned from the documents we are analyzing.

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_compare = TfidfVectorizer(vocabulary=count_vectorizer.vocabulary_).fit_transform(test_set)
print tfidf_compare.todense()

[[ 0.          0.50154891  0.70490949  0.50154891]
 [ 0.          0.4472136   0.          0.89442719]]


#####The difference between this and the hand calculated result is due to the fact that sklearn appears not to allow zeros in the $M_{idf}$ matrix
#####The bottom row of the final matrix is correct (allowing for the different order of the vocabulary)
#####The top row has additional term which alters the tf-idf weights when normalization occurs
---

---

4. Cosine Similarity
=====
***

###Dot Products

- A dot product is the multiplication of 2 vectors

- let's now consider the dot product from a geometric point of view:

<img src="./Assets/Dot_Product.png" />

####The dot product of vector $A$ times vector $B$ is defined as:

$A.B=||A||\text{  }||B||\text{  }cos\theta$

- the length of vector A times the length of vector B times the angle between them

#####So, what happens when the angle between the two vectors is 90 degrees?

<img src="./Assets/orthogonal.gif" />

#####*Q: What is the cosine of ninety degrees?*

- When the angle between the two vectors is 90 degrees, then the term $cos{\theta}$ will be zero and the resulting dot product will also be zero 

- note that although we are using 2D examples we can also calculate angles and similarity between vectors in higher dimensional spaces

- we cannot visualize or imagine what the angle between two vectors with twelve dimensions is, for example, but we can calculate it.

## 4.2 Cosine Similarity (of documents in our vector space)

- the cosine similarity between two vectors (or two documents in the Vector Space) is a measure that calculates the cosine of the angle between them

- This metric is a measurement of orientation and not magnitude

- it can be seen as a comparison between documents on a normalized space

- to calculate the cosine similarity is to solve for $cos{\theta}$:

$similarity = cos(\theta) = \frac{A.B}{||A||\text{  }||B||} = \frac{\sum^{n}_{i=1}A_{i}\times B_{i}}{\sqrt{\sum^{n}_{i=1}(A_{i})^2}\times\sqrt{\sum^{n}_{i=1}(B_{i})^{2}}}$

- Cosine Similarity will generate a metric that says how related two documents are by looking at the angle between them in vector space:

<img src="./Assets/cosine_similarity.png" />

- magnitude - meaning the term frequency is largely ignored

- so even if we have 2 vectors where one has a magnitude far exceeding the other, they could still have an small angle between them

- this is the central point for the use of Cosine Similarity, the measurement tends to ignore the higher term count on documents

<img src="./Assets/vector_space.png" />

###In Python:

In [14]:
documents = (
"The sky is blue",
"The sun is bright",
"The sun in the sky is bright",
"We can see the shining sun, the bright sun"
)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
tfidf_vectorizer = TfidfVectorizer(stop_words = "english")
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)
print tfidf_matrix.todense()
print tfidf_matrix.shape

[[ 0.78528828  0.          0.          0.6191303   0.        ]
 [ 0.          0.70710678  0.          0.          0.70710678]
 [ 0.          0.53256952  0.          0.65782931  0.53256952]
 [ 0.          0.36626037  0.57381765  0.          0.73252075]]
(4, 5)


#####Now we have the TF-IDF matrix (tfidf_matrix) for each document (the number of rows of the matrix) with 4 tf-idf terms (the number of terms used in the index vocabulary), we can calculate the Cosine Similarity between the first document (“The sky is blue”) with each of the other documents of the set:

In [23]:
print tfidf_matrix.shape

(4, 5)


In [21]:
cos_sim = cosine_similarity(tfidf_matrix[0], tfidf_matrix)
print cos_sim

[[ 1.          0.          0.40728206  0.        ]]


In [22]:
cos_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print cos_sim

[[ 1.          0.          0.40728206  0.        ]
 [ 0.          1.          0.75316704  0.77695558]
 [ 0.40728206  0.75316704  1.          0.58517734]
 [ 0.          0.77695558  0.58517734  1.        ]]


- the tfidf_matrix[0:1] is the Scipy operation to get the first row of the sparse matrix and the resulting array is the Cosine Similarity between the first document with all documents in the set. 

- Note that the first value of the array is 1.0 because it is the Cosine Similarity between the first document with itself. 

- Also note that due to the presence of similar words on the third document (“The sun in the sky is bright”), it achieved a better score.

In [19]:
import math
print cos_sim[0][2]
angle_in_radians = math.acos(cos_sim[0][2])
print math.degrees(angle_in_radians)

0.407282057783
65.9657881095
