# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
import numpy as np

### A Note About "import as"

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

<img src="http://note.io/1juA60F">



### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [24]:
# Creating arrays
a = np.zeros((2))  # Creates a list of all 0's length, 3
a

array([ 0.,  0.])

In [25]:
b = np.ones((2, 3))

b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [31]:
c = np.random.randint(1,10,(2,3,4))

c

array([[[6, 8, 3, 8],
        [9, 7, 1, 5],
        [1, 1, 6, 4]],

       [[8, 8, 3, 8],
        [1, 9, 1, 3],
        [3, 5, 5, 7]]])

In [36]:
d = np.arange(0,11,1)

What are these functions?

    arange?

In [3]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[2, 9, 6, 1],
         [5, 7, 3, 8],
         [5, 7, 1, 2]],
 
        [[9, 2, 3, 3],
         [7, 2, 5, 1],
         [2, 4, 7, 2]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [42]:
np.ndarray([1, 2, 3, 4]) + np.ndarray([1, 1, 1, 1])

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]])

In [4]:
## Arithmetic in arrays is element wise

In [46]:
def add(a, b):
    
  def add_again(b):
    return b
  # REturn values
  return a + add_again(b)

In [51]:
type(b)

numpy.ndarray

In [53]:
c = a-b
c

array([20, 29, 38, 47])

In [57]:
b**b

array([ 1,  1,  4, 27])

## Indexing, Slicing and Iterating

In [58]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [59]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [68]:
a[0:5:2]

array([ 0,  4, 16])

In [11]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [69]:
b = np.random.randint(1,100,(4,4))

In [70]:
b

array([[98, 80, 39, 78],
       [ 6, 88, 99, 18],
       [ 9, 45, 88, 41],
       [91, 32, 68, 24]])

In [72]:
# Guess the output
print(b[2,3]) # 41
print(b[0,0]) # 98

41
98


In [73]:
b[0:3,1],b[:,1]

(array([80, 88, 45]), array([80, 88, 45, 32]))

In [74]:
# b[row,co]

array([[ 6, 88, 99, 18],
       [ 9, 45, 88, 41]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [90]:
np_values = np.random.randn(6,4)
np_values

array([[ 0.62000669,  1.9615623 , -1.12421854, -0.36195641],
       [ 1.40112955, -0.24696709, -1.65676849, -0.28856141],
       [ 2.38357219, -0.30504214, -0.44981179,  0.47244654],
       [-1.5467592 ,  0.61331731,  0.87248103,  0.05490462],
       [ 0.45905279,  0.0889858 , -1.62496668,  0.32317413],
       [-1.28766641, -0.53262411,  1.85243143, -1.64719544]])

In [92]:
row_index = pd.date_range('20140101',periods=6)
row_index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [95]:
column_index = list('ABCD')

In [106]:
df = pd.DataFrame(
    data=np_values,
    columns=column_index,
    index=row_index
)

array([[ 0.62000669,  1.9615623 , -1.12421854, -0.36195641],
       [ 1.40112955, -0.24696709, -1.65676849, -0.28856141],
       [ 2.38357219, -0.30504214, -0.44981179,  0.47244654],
       [-1.5467592 ,  0.61331731,  0.87248103,  0.05490462],
       [ 0.45905279,  0.0889858 , -1.62496668,  0.32317413],
       [-1.28766641, -0.53262411,  1.85243143, -1.64719544]])

In [ ]:
df = pd.DataFrame

In [97]:
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [108]:
# Index, columns, underlying numpy data
df.T

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    0.620007    1.401130    2.383572   -1.546759    0.459053   -1.287666
B    1.961562   -0.246967   -0.305042    0.613317    0.088986   -0.532624
C   -1.124219   -1.656768   -0.449812    0.872481   -1.624967    1.852431
D   -0.361956   -0.288561    0.472447    0.054905    0.323174   -1.647195

In [109]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [113]:
df2 = pd.DataFrame([{'A' : 1,
                         'B' : 2,
                         'C' : 3,
                         'D' : 4,
                         'E' : 5}, 
                    
                    {'A' : 6,
                         'B' : 7,
                         'C' : 8,
                         'D' : 9,
                         'E' : 10}])

df2

A  B  C  D   E
0  1  2  3  4   5
1  6  7  8  9  10

In [22]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [119]:
df.head(2)

A         B         C         D
2014-01-01  0.620007  1.961562 -1.124219 -0.361956
2014-01-02  1.401130 -0.246967 -1.656768 -0.288561

In [117]:
df.tail(3)

A         B         C         D
2014-01-04 -1.546759  0.613317  0.872481  0.054905
2014-01-05  0.459053  0.088986 -1.624967  0.323174
2014-01-06 -1.287666 -0.532624  1.852431 -1.647195

In [25]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [123]:
df.describe()
df.info()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2014-01-01 to 2014-01-06
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


A    float64
B    float64
C    float64
D    float64
dtype: object

In [136]:
df.reset_index(drop=True)

index         A         B         C         D
0 2014-01-01  0.620007  1.961562 -1.124219 -0.361956
1 2014-01-02  1.401130 -0.246967 -1.656768 -0.288561
2 2014-01-03  2.383572 -0.305042 -0.449812  0.472447
3 2014-01-04 -1.546759  0.613317  0.872481  0.054905
4 2014-01-05  0.459053  0.088986 -1.624967  0.323174
5 2014-01-06 -1.287666 -0.532624  1.852431 -1.647195

### Selection

In [138]:
a = {"A": 1, "B": 2}

a["B"]

2

In [141]:
df[['A','B','C']]

A         B         C
2014-01-01  0.620007  1.961562 -1.124219
2014-01-02  1.401130 -0.246967 -1.656768
2014-01-03  2.383572 -0.305042 -0.449812
2014-01-04 -1.546759  0.613317  0.872481
2014-01-05  0.459053  0.088986 -1.624967
2014-01-06 -1.287666 -0.532624  1.852431

In [144]:
df[0:3]

A         B         C         D
2014-01-01  0.620007  1.961562 -1.124219 -0.361956
2014-01-02  1.401130 -0.246967 -1.656768 -0.288561
2014-01-03  2.383572 -0.305042 -0.449812  0.472447

In [149]:
# By label
df['Value'] # => Access columns

KeyError: 'Value'

In [150]:
# multi-axis by label
df.loc[:,['A','B']]

A         B         C         D
2014-01-01  0.620007  1.961562 -1.124219 -0.361956
2014-01-02  1.401130 -0.246967 -1.656768 -0.288561
2014-01-03  2.383572 -0.305042 -0.449812  0.472447
2014-01-04 -1.546759  0.613317  0.872481  0.054905
2014-01-05  0.459053  0.088986 -1.624967  0.323174
2014-01-06 -1.287666 -0.532624  1.852431 -1.647195

In [32]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  0.306023
2014-01-03  2.587029
2014-01-04 -0.006136

In [154]:
df.iloc[0:2, 2:4] # => iloc works on indices (int positions)

C         D
2014-01-01 -1.124219 -0.361956
2014-01-02 -1.656768 -0.288561

In [158]:
df.ix[0:2, 'B':'D']

B         C         D
2014-01-01  1.961562 -1.124219 -0.361956
2014-01-02 -0.246967 -1.656768 -0.288561

In [33]:
# Fast access to scalar
df.at[dates[1],'B']

0.30602250685205812

In [34]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04 -0.811858 -0.006136  0.156774 -1.139349
2014-01-05  0.209436  0.116989  0.858355 -0.039000
2014-01-06 -1.127558  0.288027  0.836379 -0.222454

### Boolean Indexing

In [35]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-02 -0.637398  0.306023 -0.499071  1.374214
2014-01-04 -0.811858 -0.006136  0.156774 -1.139349
2014-01-06 -1.127558  0.288027  0.836379 -0.222454

### Setting

In [36]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [37]:
df_posA

A         B         C         D
2014-01-01  0.409397  0.419996  0.220843  0.139096
2014-01-02  0.637398 -0.306023  0.499071 -1.374214
2014-01-03  0.784815  2.587029  0.741081  0.620165
2014-01-04  0.811858  0.006136 -0.156774  1.139349
2014-01-05  0.209436  0.116989  0.858355 -0.039000
2014-01-06  1.127558 -0.288027 -0.836379  0.222454

In [38]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [39]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [40]:
df['F'] = s1

In [41]:
df

A         B         C         D    F
2014-01-01  0.409397  0.419996  0.220843  0.139096  NaN
2014-01-02 -0.637398  0.306023 -0.499071  1.374214  1.0
2014-01-03  0.784815  2.587029  0.741081  0.620165  2.0
2014-01-04 -0.811858 -0.006136  0.156774 -1.139349  3.0
2014-01-05  0.209436  0.116989  0.858355 -0.039000  4.0
2014-01-06 -1.127558  0.288027  0.836379 -0.222454  5.0

### Missing Data

In [42]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [43]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [44]:
df1

A         B         C         D    F    E
2014-01-01  0.409397  0.419996  0.220843  0.139096  NaN  1.0
2014-01-02 -0.637398  0.306023 -0.499071  1.374214  1.0  1.0
2014-01-03  0.784815  2.587029  0.741081  0.620165  2.0  NaN
2014-01-04 -0.811858 -0.006136  0.156774 -1.139349  3.0  NaN

In [45]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [46]:
df.describe()

/Users/Aerlinger/.pyenv/versions/2.7.11/lib/python2.7/site-packages/numpy/lib/function_base.py:3823: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.195528  0.618655  0.385727  0.122112  3.000000
std    0.766132  0.976017  0.532018  0.842861  1.581139
min   -1.127558 -0.006136 -0.499071 -1.139349  1.000000
25%   -0.768243  0.159748  0.172791 -0.176590       NaN
50%   -0.213981  0.297025  0.480962  0.050048       NaN
75%    0.359407  0.391503  0.812554  0.499897       NaN
max    0.784815  2.587029  0.858355  1.374214  5.000000

In [47]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.195528
 B    0.618655
 C    0.385727
 D    0.122112
 F    3.000000
 dtype: float64, 2014-01-01    0.297333
 2014-01-02    0.308753
 2014-01-03    1.346618
 2014-01-04    0.239886
 2014-01-05    1.029156
 2014-01-06    0.954879
 Freq: D, dtype: float64)

### Applying functions

In [48]:
df

A         B         C         D    F
2014-01-01  0.409397  0.419996  0.220843  0.139096  NaN
2014-01-02 -0.637398  0.306023 -0.499071  1.374214  1.0
2014-01-03  0.784815  2.587029  0.741081  0.620165  2.0
2014-01-04 -0.811858 -0.006136  0.156774 -1.139349  3.0
2014-01-05  0.209436  0.116989  0.858355 -0.039000  4.0
2014-01-06 -1.127558  0.288027  0.836379 -0.222454  5.0

In [49]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  0.409397  0.419996  0.220843  0.139096   NaN
2014-01-02 -0.228001  0.726018 -0.278228  1.513310   1.0
2014-01-03  0.556814  3.313047  0.462853  2.133475   3.0
2014-01-04 -0.255045  3.306911  0.619627  0.994126   6.0
2014-01-05 -0.045609  3.423900  1.477982  0.955126  10.0
2014-01-06 -1.173167  3.711927  2.314361  0.732672  15.0

In [50]:
df.apply(lambda x: x.max() - x.min())

A    1.912373
B    2.593165
C    1.357427
D    2.513563
F    4.000000
dtype: float64

In [51]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [52]:
np.random.randn(10,4)

array([[ 1.29110867, -2.20515787,  0.4542444 , -1.30325568],
       [-0.73586007, -0.75161849,  1.54071976,  1.89420031],
       [ 2.07229294, -0.13116767, -0.72586537,  1.8278182 ],
       [ 1.99550822,  0.48951297, -1.48322983, -0.16130745],
       [-1.21217277, -0.62643467,  0.14054465,  1.10886675],
       [-0.37935773, -1.53905626,  0.00346257, -0.55241566],
       [-0.39311126,  0.89852676,  0.96201889, -0.02480679],
       [-0.67553271,  0.52364647, -0.01907428, -1.66062382],
       [-0.59543693,  1.31532212, -1.86194666,  0.23545243],
       [ 1.04283634, -0.73182667, -0.55889171, -1.41724356]])

In [53]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -1.561838 -0.068824 -0.908736  0.821195
1 -1.221536 -0.221494  0.508220 -2.036055
2 -0.714067  1.613831  0.225931  0.226107
3 -1.071052 -1.605836  0.812148 -0.120937
4  2.119807 -1.153335  0.444468  0.587185
5  0.814886 -1.185398  3.271914 -0.467837
6  0.335155  0.305330 -0.268205 -0.558633
7 -2.199184 -0.344612 -0.297550  0.415522
8 -0.491293  1.544236 -0.673718  0.185804
9  0.849442 -0.726972 -0.605858 -1.247690

In [54]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -1.561838 -0.068824 -0.908736  0.821195
 1 -1.221536 -0.221494  0.508220 -2.036055
 2 -0.714067  1.613831  0.225931  0.226107,
           0         1         2         3
 3 -1.071052 -1.605836  0.812148 -0.120937
 4  2.119807 -1.153335  0.444468  0.587185
 5  0.814886 -1.185398  3.271914 -0.467837
 6  0.335155  0.305330 -0.268205 -0.558633,
           0         1         2         3
 7 -2.199184 -0.344612 -0.297550  0.415522
 8 -0.491293  1.544236 -0.673718  0.185804
 9  0.849442 -0.726972 -0.605858 -1.247690]

In [55]:
pd.concat(pieces)

0         1         2         3
0 -1.561838 -0.068824 -0.908736  0.821195
1 -1.221536 -0.221494  0.508220 -2.036055
2 -0.714067  1.613831  0.225931  0.226107
3 -1.071052 -1.605836  0.812148 -0.120937
4  2.119807 -1.153335  0.444468  0.587185
5  0.814886 -1.185398  3.271914 -0.467837
6  0.335155  0.305330 -0.268205 -0.558633
7 -2.199184 -0.344612 -0.297550  0.415522
8 -0.491293  1.544236 -0.673718  0.185804
9  0.849442 -0.726972 -0.605858 -1.247690

In [56]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -1.561838 -0.068824 -0.908736  0.821195
1 -1.221536 -0.221494  0.508220 -2.036055
2 -0.714067  1.613831  0.225931  0.226107
3 -1.071052 -1.605836  0.812148 -0.120937
4  2.119807 -1.153335  0.444468  0.587185
5  0.814886 -1.185398  3.271914 -0.467837
6  0.335155  0.305330 -0.268205 -0.558633
7 -2.199184 -0.344612 -0.297550  0.415522
8 -0.491293  1.544236 -0.673718  0.185804
9  0.849442 -0.726972 -0.605858 -1.247690

### Grouping


In [57]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [58]:
df

A      B         C         D
0  foo    one -1.437387  1.352577
1  bar    one -0.794866 -0.937865
2  foo    two  0.915232  0.275579
3  bar  three  1.176147  0.065104
4  foo    two  0.342110  0.273876
5  bar    two -0.629052  0.798924
6  foo    one  0.159179 -0.456231
7  foo  three -0.662512 -0.091937

In [59]:
pd.pivot_table(df, index=['A'], columns=['B'], values='C', aggfunc='max')

B         one     three       two
A                                
bar -0.794866  1.176147 -0.629052
foo  0.159179 -0.662512  0.915232

In [60]:
df.pivot(index='A', columns='B', aggfunc='sum')

TypeError: pivot() got an unexpected keyword argument 'aggfunc'

In [ ]:
df.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df.groupby(['A','B']).sum()

In [ ]:
df.

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min',how='mean') # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
%matplotlib inline

df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

In [ ]:
df

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas